DROP DATABASE IF EXISTS DB_TCCGrupo4;

CREATE DATABASE DB_TCCGrupo4;
USE DB_TCCGrupo4;

CREATE TABLE USUARIO (
    IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , EMAIL VARCHAR(100)
    , SENHA VARCHAR(45)
);

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDUSUARIO INT NOT NULL
	, NOME VARCHAR(100)
	, TELRESIDENCIAL VARCHAR(15)
	, TELCELULAR VARCHAR(15)
	, RUA VARCHAR(100)
	, NUMERO INT
	, COMPLEMENTO VARCHAR(100)
	, BAIRRO VARCHAR(100)
	, CEP CHAR(8)
	, CIDADE VARCHAR(100)
	, ESTADO CHAR(2)
	, CONSTRAINT FK_PESSOA_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
) ENGINE INNODB;

CREATE TABLE FISICA (
	IDFISICA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDPESSOA INT NOT NULL
	, CPF CHAR(11)
	, CONSTRAINT FK_FISICA_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA)
) ENGINE INNODB;

CREATE TABLE JURICA (
	IDJURICA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDPESSOA INT NOT NULL
	, CNPJ CHAR(11)
	, CONSTRAINT FK_JURICA_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA)
) ENGINE INNODB;

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDUSUARIO INT NOT NULL
	, NOME VARCHAR(100)
	, TELEFONE_CELULAR VARCHAR(15)
	, ADMINISTRADOR ENUM ('SIM', 'NAO')
	, CONSTRAINT FK_FUNCIONARIO_USUARIO  FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
) ENGINE INNODB;

CREATE TABLE PREVENTIVA (
	IDPREVENTIVA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDPESSOA INT NOT NULL
	, DESCRICAO TEXT
	, INTERVALO INT
	, PERIODO ENUM('DIA', 'MÊS', 'ANO')
	, CONSTRAINT FK_PRECENTIVA_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA)
) ENGINE INNODB;

CREATE TABLE CHAMADO (
	IDCHAMADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDPESSOA INT NOT NULL
	, IDPREVENTIVA INT
	, TELEFONE_CONTATO VARCHAR(15)
	, TELEFONE_CELULAR VARCHAR(15)
	, DT_CHAMADO DATE
	, EMAIL VARCHAR(100)
	, NOME VARCHAR(100)
	, DESCRICAO TEXT
	, RUA VARCHAR(100)
	, NUMERO INT
	, COMPLEMENTO VARCHAR(100)
	, BAIRRO VARCHAR(100)
	, CEP CHAR(8)
	, CIDADE VARCHAR(100)
	, ESTADO CHAR(8)
	, SITUACAO ENUM('PENDENTE', 'EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO', 'EM ESPERA')
	, CONSTRAINT FK_CHAMADO_PESSOA FOREIGN KEY(IDPESSOA) REFERENCES PESSOA (IDPESSOA)
	, CONSTRAINT FK_CHAMADO_PREVENTIVA FOREIGN KEY(IDPREVENTIVA) REFERENCES PREVENTIVA (IDPREVENTIVA)
) ENGINE INNODB;

CREATE TABLE OCORRENCIA (
	IDOCORRENCIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDCHAMADO INT NOT NULL
	, IDUSUARIO INT NOT NULL
	, DESCRICAO TEXT
	, DT_OCORRENCIA DATETIME 
	, CONSTRAINT FK_OCORRENCIA_CHAMADO FOREIGN KEY(IDCHAMADO) REFERENCES CHAMADO (IDCHAMADO)
	, CONSTRAINT FK_OCORRENCIA_USUARIO FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
) ENGINE INNODB;

CREATE TABLE EXECUTA (
	IDFUNCIONARIO INT NOT NULL
	, IDCHAMADO INT NOT NULL
	, CONSTRAINT PK_EXECUTA PRIMARY KEY (IDFUNCIONARIO, IDCHAMADO)
	, CONSTRAINT FK_EXECUTA_FUNCIONARIO FOREIGN KEY(IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO)
	, CONSTRAINT FK_EXECUTA_CHAMADO FOREIGN KEY(IDCHAMADO) REFERENCES CHAMADO (IDCHAMADO)
) ENGINE INNODB;

